config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  post 'new_game', to: "rooms#new_game"
  post 'play', to: 'rooms#play', as: 'play'
  resources :rooms
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/room.rb
class Room < ApplicationRecord
  require 'securerandom'
  extend FriendlyId
  friendly_id :slug_candidates, use: :slugged
  belongs_to :user
  def slug_candidates
    attempts = 0
    slug_length = 4
    slug = SecureRandom.alphanumeric(slug_length)

    while Room.where(slug:).exists?
      attempts += 1
      slug_length += 1 if attempts > 10
      attempts = 0
      slug = SecureRandom.alphanumeric(slug_length)
    end

    slug
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :rooms, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: %i[show edit update destroy]
  before_action :authenticate_user!, only: %i[new_game]

  # GET /rooms or /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1 or /rooms/1.json
  def show; end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit; end

  # POST /rooms or /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to room_url(@room), notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1 or /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to room_url(@room), notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1 or /rooms/1.json
  def destroy
    @room.destroy

    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def new_game
    @room = Room.new
    @room.user = current_user
    @room.save

    render turbo_stream:
      turbo_stream.update('room_code', partial: 'pages/room_code', locals: { room: @room })
  end

  def new_game
    @room = Room.new
    @room.user = current_user
    @room.save

    render turbo_stream:
      turbo_stream.update('room_code', partial: 'pages/room_code', locals: {room: @room})
  end

  def play
    @room = Room.friendly.find(params[:room][:slug].downcase)
    # set session player name to the name in the form
    session[:player_name] = params[:room][:player_name]
    redirect_to room_url(@room)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_room
    @room = Room.friendly.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def room_params
    params.require(:room).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsInRooms</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/_room_code.html.erb
<% if room.present? %>
    <div class="d-flex justify-content-center">
    <div class="card mx-auto" style="width: 400px; height: 250px;">
    <div class="card-header">
        <h3 class="card-title">Room code</h3>
    </div>
    <div class="card-body">
        <p class="card-text">Your room code is <%= room.slug.upcase %></p>
        <p class="card-text">Share this code with your friends to join the room</p>
        <p class="card-text">Click the button below to start the game</p>
        <%= button_to "Start Game", room_path(room), method: :get %>
        </div>
        </div>
        </div>
        <% end %>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>
<% if current_user %>
  <%= content_tag(:h3, current_user.email) %>
  <%= button_to "Start A New Game!", new_game_path %>
  <%= link_to "Logout", destroy_user_session_path, data: { turbo_method: :delete } %>
<% else %>
  <%= link_to "Login", new_user_session_path %>
  <%= link_to "Sign Up", new_user_registration_path %>
<% end %>
<%= turbo_frame_tag "room_code" do %>
  <%= render partial: "pages/room_code", locals: {room: nil} %>
<% end %>
<%= simple_form_for(:room, url: play_path(slug: "")) do |f| %>
  <%= f.input :slug, placeholder: "ENTER 4-LETTER CODE", name: "slug" %>
  <%= f.input :player_name, placeholder: "ENTER YOUR NAME", input_html: {maxlength: 12} %>
  <%= f.button :submit, "PLAY", class: "btn btn-secondary" %>
<% end %>

app/views/rooms/_form.html.erb
<%= simple_form_for(@room) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/rooms/_room.html.erb
<div id="<%= dom_id room %>">
  <% if current_user %>
    <p>
      <strong>Player Name:</strong>
      <%= current_user.email %>
    </p>
  <% else %>
    <p>
      <strong>Player Name:</strong>
      <%= session[:player_name] %>
    </p>
  <% end %>
  <p>
    <strong>Slug:</strong>
    <%= room.slug %>
  </p>
</div>

app/views/rooms/edit.html.erb
<h1>Editing room</h1>

<%= render "form", room: @room %>

<br>

<div>
  <%= link_to "Show this room", @room %> |
  <%= link_to "Back to rooms", rooms_path %>
</div>

app/views/rooms/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Rooms</h1>

<div id="rooms">
  <% @rooms.each do |room| %>
    <%= render room %>
    <p>
      <%= link_to "Show this room", room %>
    </p>
  <% end %>
</div>

<%= link_to "New room", new_room_path %>

app/views/rooms/new.html.erb
<h1>New room</h1>

<%= render "form", room: @room %>

<br>

<div>
  <%= link_to "Back to rooms", rooms_path %>
</div>

app/views/rooms/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @room %>

<div>
  <%= link_to "Edit this room", edit_room_path(@room) %> |
  <%= link_to "Back to rooms", rooms_path %>

  <%= button_to "Destroy this room", @room, method: :delete %>
</div>